
services:
  ### 🔹 Spring Boot 컨테이너
  spring-app:
    build:
      context: . # Dockerfile 이 있는 위치
      dockerfile: Dockerfile
    image:
      psb3707/hongik-mentor-spring-app:latest
    container_name: spring-app
    depends_on:
      - logstash
#      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network
#  mysql:
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: psb011031!
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: psb011031!
#    ports:
#      - "3308:3306"
#    networks:
#      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    restart: always  # 컨테이너가 중지되면 자동 재시작
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    restart: always  # 컨테이너가 중지되면 자동 재시작
    ports:
      - "5044:5044"  # Beats input
      - "9600:9600"  # Monitoring API
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # 로컬 logstash.conf 파일 마운트
    networks:
      - app-network
  kibana:
    image: kibana:8.10.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network
  ## nginx
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  app-network:
    driver: bridge

