input {
    tcp {
        port => 5044
        codec => json
    }
}

filter {
  # "message" 필드가 존재하고 JSON 형식일 경우만 파싱
  if [message] and [message] =~ "{" {
      json {
          source => "message"
          target => "parsed_json"
          add_tag => ["json_parsed"]
      }

      # JSON 내부 필드를 최상위로 이동 (message 필드 대체)
      mutate {
          add_field => {
              "method" => "%{[parsed_json][method]}"
              "path" => "%{[parsed_json][path]}"
              "status" => "%{[parsed_json][status]}"
              "latency" => "%{[parsed_json][latency]}"
              "timestamp" => "%{[parsed_json][timestamp]}"
          }
          remove_field => ["message", "parsed_json"]
      }
  }

  # latency 값을 정수(integer)로 변환 (빈 값이 아닐 경우만)
  if [latency] and [latency] != "" {
      mutate {
          convert => { "latency" => "integer" }
      }
  }
}

output {

    stdout { codec => rubydebug }

    if [latency] {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "api-latency-logs-%{+YYYY.MM.dd}"
        }
    } else {
        # 일반 로그 저장
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "application-logs-%{+YYYY.MM.dd}"
        }
    }
}
